version: '3.8'

services:
  database:
    image: postgres:16-alpine
    container_name: devroast_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devroast
    ports:
      - "5432:5432"
    volumes:
      - devroast_pgdata:/var/lib/postgresql/data

volumes:
  devroast_pgdata:
